import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    ignores: [
      'dist/**',
      'release/**',
      'coverage/**',
      'node_modules/**',
      // Generated by scripts/safari.mjs: an Xcode project wrapping a copy of
      // dist/chrome, regenerated on demand rather than edited.
      'safari/**',
      // Scratch snippets evaluated inside a page, and the driven browser's profile.
      // Skill packs vendored by tooling; not this project's source.
      '.agents/**',
      'probe-out/**',
      '.browser-profile/**',
      'tools/dom-probe.js',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['src/**/*.ts'],
    languageOptions: {
      globals: { ...globals.browser, ...globals.webextensions },
    },
    rules: {
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'always'],
      'prefer-const': 'error',
    },
  },
  {
    // Build and tooling scripts run in Node, but the Playwright ones also carry
    // callbacks that are serialised into a page, so both global sets apply.
    files: ['scripts/**/*.mjs', 'scripts/**/*.js'],
    languageOptions: { globals: { ...globals.node, ...globals.browser } },
    rules: { 'no-console': 'off' },
  },
  {
    files: ['tests/**/*.ts'],
    languageOptions: { globals: { ...globals.node } },
  },
  {
    // Console snippets pasted into a Bale tab: browser globals, and they are
    // written to be read and edited in DevTools rather than bundled.
    files: ['tools/**/*.js'],
    languageOptions: { globals: { ...globals.browser } },
    rules: { 'no-console': 'off' },
  },
);
